services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      red_entorno:
        ipv4_address: 192.168.30.10

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml:ro
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      red_entorno:
        ipv4_address: 192.168.30.11

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - ../resultados:/resultados
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      red_entorno:
        ipv4_address: 192.168.30.12

volumes:
  grafana_data: {}

networks:
  red_entorno:
    external: true
