
services:
  parser:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: parser
    restart: "no"
    volumes:
      - ../logs:/logs
      - ../resultados:/resultados
    networks:
      red_entorno:
        ipv4_address: 192.168.30.200

networks:
  red_entorno:
    external: true