services: 
    web1:
        image: jorgelpz-apache-image:p1
        ports:
        - "8081:80"
        volumes:
        - ./web_jorgelpz:/var/www/html
        networks:
        - red_web
        - red_servicios

    web2:
        image: jorgelpz-apache-image:p1
        ports:
        - "8082:80"
        volumes:
        - ./web_jorgelpz:/var/www/html
        networks:
        - red_web
        - red_servicios

    web3:
        image: jorgelpz-apache-image:p1
        ports:
        - "8083:80"
        volumes:
        - ./web_jorgelpz:/var/www/html
        networks:
        - red_web
        - red_servicios

    web4:
        image: jorgelpz-apache-image:p1
        ports:
        - "8084:80"
        volumes:
        - ./web_jorgelpz:/var/www/html
        networks:
        - red_web
        - red_servicios

    web5:
        image: jorgelpz-apache-image:p1
        ports:
        - "8085:80"
        volumes:
        - ./web_jorgelpz:/var/www/html
        networks:
        - red_web
        - red_servicios

    web6:
        image: jorgelpz-apache-image:p1
        ports:
        - "8086:80"
        volumes:
        - ./web_jorgelpz:/var/www/html
        networks:
        - red_web
        - red_servicios

    web7:
        image: jorgelpz-apache-image:p1
        ports:
        - "8087:80"
        volumes:
        - ./web_jorgelpz:/var/www/html
        networks:
        - red_web
        - red_servicios

    web8:
        image: jorgelpz-apache-image:p1
        ports:
        - "8088:80"
        volumes:
        - ./web_jorgelpz:/var/www/html
        networks:
        - red_web
        - red_servicios

networks:
  red_web:
    external: true
  red_servicios:
    external: true