services: 
    balanceador-nginx:
        # Crea el balanceador con Nginx a partir de la imagen jorgelpz-nginx-image:p2
        # gerenada a su vez a partir del DockerfileNginx_jorgelpz siendo este una
        # modificación del Dockerfile usado en la práctica 1
        image: jorgelpz-nginx-image:p2
        container_name: balanceador-nginx
        ports:
        # El balanceador esta en el localhost:9090 y las
        # estadísitcas en localhost:9090/estadisticas_jorgelpz
        - "9090:80"
        volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        networks:
            red_web:
                #ip que ocupa dentro de la subred red_web
                ipv4_address: 192.168.10.50 

networks:
    red_web:
        external: true
    red_servicios:
        external: true